sources:
  - name: AlfaFrens
    handler:
      graphql:
        endpoint: '{context.url:https://api.goldsky.com/api/public/project_clsnd6xsoma5j012qepvucfpp/subgraphs/alfafrens/4.2.4/gn}'
    transforms:
      - autoPagination:
          validateSchema: true # Validates that the schema source actually contains the required input filters.
          limitOfRecords: 1000 # Default is 1000, you can change if you indexer has different configuration in GRAPH_GRAPHQL_MAX_FIRST var.

documents: ["./graphql/*.{gql,graphql}"]
codegen:
  scalars:
    BigInt: string
    Bytes: string
    BigDecimal: string